/*

{
        "audio": true,
        "audio_record_all": true,
        "audio_record_limit_time": 100,
        "autonomous_limit_count_questionnare": 15,
        "autonomous_limit_time_questionnare": 300,
        "config_date": "2023-09-22 12:45:25",
        "config_id": "363950f08963ba085ea7",
        "dt_reloading_config": -1,
        "force_auto_time": false,
        "force_gps": false,
        "gps": true,
        "has_registration": false,
        "is_critical_update": false,
        "is_force_audio": false,
        "last_app_version_code": 0,
        "login_admin": "alina",
        "min_ver_android_app": 2290801,
        "photo_questionnaire": true,
        "project_info": {
        "billing_questions": 6,
        "elements": [
        {
        "contents": [],
        "elements": [
        {
        "contents": [],
        "endTime": 0,
        "isChecked": false,
        "isEnabled": true,
        "isQuestionShowing": false,
        "isScreenShowing": false,
        "isShuffeled": false,
        "isShuffeledIntoBox": false,
        "options": {
        "auto_check": false,
        "fixed_order": false,
        "flip_cols_and_rows": false,
        "helper": false,
        "is_media": false,
        "jump": 21,
        "max_number": 100,
        "min_number": 1,
        "open_type": "number",
        "order": 1,
        "photo_answer": false,
        "photo_answer_required": false,
        "placeholder": "",
        "polyanswer": false,
        "record_sound": false,
        "rotation": false,
        "search": false,
        "show_images": false,
        "show_scale": false,
        "small_column": false,
        "take_photo": false,
        "title": "1",
        "unchecker": false,
        "unnecessary_fill_open": false
        },
        "queryVisibility": 0,
        "relative_id": 2,
        "relative_parent_id": 1,
        "startTime": 0,
        "type": "answer"
        },
        {
        "endTime": 0,
        "isChecked": false,
        "isEnabled": true,
        "isQuestionShowing": false,
        "isScreenShowing": false,
        "isShuffeled": false,
        "isShuffeledIntoBox": false,
        "options": {
        "auto_check": false,
        "fixed_order": false,
        "flip_cols_and_rows": false,
        "helper": false,
        "is_media": false,
        "jump": 21,
        "order": 2,
        "photo_answer": false,
        "photo_answer_required": false,
        "polyanswer": false,
        "record_sound": false,
        "rotation": false,
        "search": false,
        "show_images": false,
        "show_scale": false,
        "small_column": false,
        "take_photo": false,
        "title": "НОВЫЙ - Ответ",
        "unchecker": false,
        "unnecessary_fill_open": false
        },
        "queryVisibility": 0,
        "relative_id": 20,
        "relative_parent_id": 1,
        "startTime": 0,
        "type": "answer"
        }
        ],
        "endTime": 0,
        "isChecked": false,
        "isEnabled": true,
        "isQuestionShowing": false,
        "isScreenShowing": false,
        "isShuffeled": false,
        "isShuffeledIntoBox": false,
        "options": {
        "auto_check": false,
        "fixed_order": false,
        "flip_cols_and_rows": false,
        "helper": false,
        "is_media": false,
        "number": 1,
        "order": 1,
        "photo_answer": false,
        "photo_answer_required": false,
        "polyanswer": false,
        "record_sound": false,
        "rotation": false,
        "search": false,
        "show_images": false,
        "show_scale": false,
        "small_column": false,
        "take_photo": false,
        "title": "НОВЫЙ Вопрос-список",
        "unchecker": false,
        "unnecessary_fill_open": false
        },
        "queryVisibility": 0,
        "relative_id": 1,
        "relative_parent_id": 0,
        "startTime": 0,
        "subtype": "list",
        "type": "question"
        },
        {
        "contents": [],
        "elements": [
        {
        "endTime": 0,
        "isChecked": false,
        "isEnabled": true,
        "isQuestionShowing": false,
        "isScreenShowing": false,
        "isShuffeled": false,
        "isShuffeledIntoBox": false,
        "options": {
        "auto_check": false,
        "fixed_order": false,
        "flip_cols_and_rows": false,
        "helper": false,
        "is_media": false,
        "jump": 3,
        "order": 1,
        "photo_answer": false,
        "photo_answer_required": false,
        "polyanswer": false,
        "prev_condition": "$e.2.checked < 20",
        "record_sound": false,
        "rotation": false,
        "search": false,
        "show_images": false,
        "show_scale": false,
        "small_column": false,
        "take_photo": false,
        "title": "НОВЫЙ - Ответ",
        "unchecker": false,
        "unnecessary_fill_open": false
        },
        "queryVisibility": 0,
        "relative_id": 22,
        "relative_parent_id": 21,
        "startTime": 0,
        "type": "answer"
        }
        ],
        "endTime": 0,
        "isChecked": false,
        "isEnabled": true,
        "isQuestionShowing": false,
        "isScreenShowing": false,
        "isShuffeled": false,
        "isShuffeledIntoBox": false,
        "options": {
        "auto_check": false,
        "fixed_order": false,
        "flip_cols_and_rows": false,
        "helper": false,
        "is_media": false,
        "jump": 3,
        "number": 2,
        "order": 2,
        "photo_answer": false,
        "photo_answer_required": false,
        "polyanswer": true,
        "record_sound": false,
        "rotation": false,
        "search": false,
        "show_images": false,
        "show_scale": false,
        "small_column": false,
        "take_photo": false,
        "title": "Скрытый",
        "unchecker": false,
        "unnecessary_fill_open": false
        },
        "queryVisibility": 0,
        "relative_id": 21,
        "relative_parent_id": 0,
        "startTime": 0,
        "subtype": "hidden",
        "type": "question"
        },
        {
        "contents": [],
        "elements": [
        {
        "contents": [],
        "elements": [
        {
        "contents": [],
        "endTime": 0,
        "isChecked": false,
        "isEnabled": true,
        "isQuestionShowing": false,
        "isScreenShowing": false,
        "isShuffeled": false,
        "isShuffeledIntoBox": false,
        "options": {
        "auto_check": false,
        "fixed_order": false,
        "flip_cols_and_rows": false,
        "helper": false,
        "is_media": false,
        "jump": 7,
        "order": 1,
        "photo_answer": false,
        "photo_answer_required": false,
        "polyanswer": false,
        "record_sound": false,
        "rotation": false,
        "search": false,
        "show_images": false,
        "show_scale": false,
        "small_column": false,
        "take_photo": false,
        "title": "м",
        "unchecker": false,
        "unnecessary_fill_open": false
        },
        "queryVisibility": 0,
        "relative_id": 5,
        "relative_parent_id": 4,
        "startTime": 0,
        "type": "answer"
        },
        {
        "contents": [],
        "endTime": 0,
        "isChecked": false,
        "isEnabled": true,
        "isQuestionShowing": false,
        "isScreenShowing": false,
        "isShuffeled": false,
        "isShuffeledIntoBox": false,
        "options": {
        "auto_check": false,
        "fixed_order": false,
        "flip_cols_and_rows": false,
        "helper": false,
        "is_media": false,
        "jump": 7,
        "order": 2,
        "photo_answer": false,
        "photo_answer_required": false,
        "polyanswer": false,
        "record_sound": false,
        "rotation": false,
        "search": false,
        "show_images": false,
        "show_scale": false,
        "small_column": false,
        "take_photo": false,
        "title": "ж",
        "unchecker": false,
        "unnecessary_fill_open": false
        },
        "queryVisibility": 0,
        "relative_id": 6,
        "relative_parent_id": 4,
        "startTime": 0,
        "type": "answer"
        },
        {
        "endTime": 0,
        "isChecked": false,
        "isEnabled": true,
        "isQuestionShowing": false,
        "isScreenShowing": false,
        "isShuffeled": false,
        "isShuffeledIntoBox": false,
        "options": {
        "auto_check": false,
        "fixed_order": false,
        "flip_cols_and_rows": false,
        "helper": true,
        "is_media": false,
        "jump": 7,
        "order": 3,
        "photo_answer": false,
        "photo_answer_required": false,
        "polyanswer": false,
        "record_sound": false,
        "rotation": false,
        "search": false,
        "show_images": false,
        "show_scale": false,
        "small_column": false,
        "take_photo": false,
        "unchecker": false,
        "unnecessary_fill_open": false
        },
        "queryVisibility": 0,
        "relative_id": 1000001,
        "relative_parent_id": 4,
        "startTime": 0,
        "type": "answer"
        }
        ],
        "endTime": 0,
        "isChecked": false,
        "isEnabled": true,
        "isQuestionShowing": false,
        "isScreenShowing": false,
        "isShuffeled": false,
        "isShuffeledIntoBox": false,
        "options": {
        "auto_check": false,
        "fixed_order": false,
        "flip_cols_and_rows": false,
        "helper": false,
        "is_media": false,
        "number": 3,
        "order": 1,
        "photo_answer": false,
        "photo_answer_required": false,
        "polyanswer": false,
        "record_sound": false,
        "rotation": false,
        "search": false,
        "show_images": false,
        "show_scale": false,
        "small_column": false,
        "take_photo": false,
        "title": "пол",
        "unchecker": false,
        "unnecessary_fill_open": false
        },
        "queryVisibility": 0,
        "relative_id": 4,
        "relative_parent_id": 3,
        "startTime": 0,
        "subtype": "list",
        "type": "question"
        },
        {
        "contents": [],
        "elements": [
        {
        "contents": [],
        "endTime": 0,
        "isChecked": false,
        "isEnabled": true,
        "isQuestionShowing": false,
        "isScreenShowing": false,
        "isShuffeled": false,
        "isShuffeledIntoBox": false,
        "options": {
        "auto_check": false,
        "fixed_order": false,
        "flip_cols_and_rows": false,
        "helper": false,
        "is_media": false,
        "jump": 9,
        "open_type": "text",
        "order": 1,
        "photo_answer": false,
        "photo_answer_required": false,
        "placeholder": "",
        "polyanswer": false,
        "record_sound": false,
        "rotation": false,
        "search": false,
        "show_images": false,
        "show_scale": false,
        "small_column": false,
        "take_photo": false,
        "title": "введите",
        "unchecker": false,
        "unnecessary_fill_open": false
        },
        "queryVisibility": 0,
        "relative_id": 8,
        "relative_parent_id": 7,
        "startTime": 0,
        "type": "answer"
        },
        {
        "contents": [],
        "endTime": 0,
        "isChecked": false,
        "isEnabled": true,
        "isQuestionShowing": false,
        "isScreenShowing": false,
        "isShuffeled": false,
        "isShuffeledIntoBox": false,
        "options": {
        "auto_check": false,
        "fixed_order": false,
        "flip_cols_and_rows": false,
        "helper": false,
        "is_media": false,
        "jump": 9,
        "order": 2,
        "photo_answer": false,
        "photo_answer_required": false,
        "polyanswer": false,
        "record_sound": false,
        "rotation": false,
        "search": false,
        "show_images": false,
        "show_scale": false,
        "small_column": false,
        "take_photo": false,
        "title": "отказ",
        "unchecker": false,
        "unnecessary_fill_open": false
        },
        "queryVisibility": 0,
        "relative_id": 15,
        "relative_parent_id": 7,
        "startTime": 0,
        "type": "answer"
        },
        {
        "endTime": 0,
        "isChecked": false,
        "isEnabled": true,
        "isQuestionShowing": false,
        "isScreenShowing": false,
        "isShuffeled": false,
        "isShuffeledIntoBox": false,
        "options": {
        "auto_check": false,
        "fixed_order": false,
        "flip_cols_and_rows": false,
        "helper": true,
        "is_media": false,
        "jump": 9,
        "order": 3,
        "photo_answer": false,
        "photo_answer_required": false,
        "polyanswer": false,
        "record_sound": false,
        "rotation": false,
        "search": false,
        "show_images": false,
        "show_scale": false,
        "small_column": false,
        "take_photo": false,
        "unchecker": false,
        "unnecessary_fill_open": false
        },
        "queryVisibility": 0,
        "relative_id": 1000002,
        "relative_parent_id": 7,
        "startTime": 0,
        "type": "answer"
        }
        ],
        "endTime": 0,
        "isChecked": false,
        "isEnabled": true,
        "isQuestionShowing": false,
        "isScreenShowing": false,
        "isShuffeled": false,
        "isShuffeledIntoBox": false,
        "options": {
        "auto_check": false,
        "fixed_order": false,
        "flip_cols_and_rows": false,
        "helper": false,
        "is_media": false,
        "number": 4,
        "order": 2,
        "photo_answer": false,
        "photo_answer_required": false,
        "polyanswer": false,
        "record_sound": false,
        "rotation": false,
        "search": false,
        "show_images": false,
        "show_scale": false,
        "small_column": false,
        "take_photo": false,
        "title": "возраст",
        "unchecker": false,
        "unnecessary_fill_open": false
        },
        "queryVisibility": 0,
        "relative_id": 7,
        "relative_parent_id": 3,
        "startTime": 0,
        "subtype": "list",
        "type": "question"
        },
        {
        "contents": [],
        "elements": [
        {
        "contents": [],
        "endTime": 0,
        "isChecked": false,
        "isEnabled": true,
        "isQuestionShowing": false,
        "isScreenShowing": false,
        "isShuffeled": false,
        "isShuffeledIntoBox": false,
        "options": {
        "auto_check": false,
        "fixed_order": false,
        "flip_cols_and_rows": false,
        "helper": false,
        "is_media": false,
        "jump": 13,
        "order": 1,
        "photo_answer": false,
        "photo_answer_required": false,
        "polyanswer": false,
        "prev_condition": "1 < $e.8.value <18",
        "record_sound": false,
        "rotation": false,
        "search": false,
        "show_images": false,
        "show_scale": false,
        "small_column": false,
        "take_photo": false,
        "title": "18-",
        "unchecker": false,
        "unnecessary_fill_open": false
        },
        "queryVisibility": 0,
        "relative_id": 10,
        "relative_parent_id": 9,
        "startTime": 0,
        "type": "answer"
        },
        {
        "contents": [],
        "endTime": 0,
        "isChecked": false,
        "isEnabled": true,
        "isQuestionShowing": false,
        "isScreenShowing": false,
        "isShuffeled": false,
        "isShuffeledIntoBox": false,
        "options": {
        "auto_check": false,
        "fixed_order": false,
        "flip_cols_and_rows": false,
        "helper": false,
        "is_media": false,
        "jump": 13,
        "order": 2,
        "photo_answer": false,
        "photo_answer_required": false,
        "polyanswer": false,
        "prev_condition": "100 > $e.8.value >= 18",
        "record_sound": false,
        "rotation": false,
        "search": false,
        "show_images": false,
        "show_scale": false,
        "small_column": false,
        "take_photo": false,
        "title": "18+",
        "unchecker": false,
        "unnecessary_fill_open": false
        },
        "queryVisibility": 0,
        "relative_id": 11,
        "relative_parent_id": 9,
        "startTime": 0,
        "type": "answer"
        },
        {
        "contents": [],
        "endTime": 0,
        "isChecked": false,
        "isEnabled": true,
        "isQuestionShowing": false,
        "isScreenShowing": false,
        "isShuffeled": false,
        "isShuffeledIntoBox": false,
        "options": {
        "auto_check": false,
        "fixed_order": false,
        "flip_cols_and_rows": false,
        "helper": false,
        "is_media": false,
        "jump": 13,
        "order": 3,
        "photo_answer": false,
        "photo_answer_required": false,
        "polyanswer": false,
        "prev_condition": "16 <= $e.8.value <=21",
        "record_sound": false,
        "rotation": false,
        "search": false,
        "show_images": false,
        "show_scale": false,
        "small_column": false,
        "take_photo": false,
        "title": "16-21",
        "unchecker": false,
        "unnecessary_fill_open": false
        },
        "queryVisibility": 0,
        "relative_id": 12,
        "relative_parent_id": 9,
        "startTime": 0,
        "type": "answer"
        }
        ],
        "endTime": 0,
        "isChecked": false,
        "isEnabled": true,
        "isQuestionShowing": false,
        "isScreenShowing": false,
        "isShuffeled": false,
        "isShuffeledIntoBox": false,
        "options": {
        "auto_check": false,
        "fixed_order": false,
        "flip_cols_and_rows": false,
        "helper": false,
        "is_media": false,
        "jump": 13,
        "number": 5,
        "order": 3,
        "photo_answer": false,
        "photo_answer_required": false,
        "polyanswer": true,
        "record_sound": false,
        "rotation": false,
        "search": false,
        "show_images": false,
        "show_scale": false,
        "small_column": false,
        "take_photo": false,
        "title": "Скрытый",
        "unchecker": false,
        "unnecessary_fill_open": false
        },
        "queryVisibility": 0,
        "relative_id": 9,
        "relative_parent_id": 3,
        "startTime": 0,
        "subtype": "hidden",
        "type": "question"
        }
        ],
        "endTime": 0,
        "isChecked": false,
        "isEnabled": true,
        "isQuestionShowing": false,
        "isScreenShowing": false,
        "isShuffeled": false,
        "isShuffeledIntoBox": false,
        "options": {
        "auto_check": false,
        "fixed_order": false,
        "flip_cols_and_rows": false,
        "helper": false,
        "is_media": false,
        "order": 3,
        "photo_answer": false,
        "photo_answer_required": false,
        "polyanswer": false,
        "record_sound": false,
        "rotation": false,
        "search": false,
        "show_images": false,
        "show_scale": false,
        "small_column": false,
        "take_photo": false,
        "unchecker": false,
        "unnecessary_fill_open": false
        },
        "queryVisibility": 0,
        "relative_id": 3,
        "relative_parent_id": 0,
        "startTime": 0,
        "subtype": "quota",
        "type": "box"
        },
        {
        "contents": [],
        "elements": [
        {
        "contents": [],
        "endTime": 0,
        "isChecked": false,
        "isEnabled": true,
        "isQuestionShowing": false,
        "isScreenShowing": false,
        "isShuffeled": false,
        "isShuffeledIntoBox": false,
        "options": {
        "auto_check": false,
        "fixed_order": false,
        "flip_cols_and_rows": false,
        "helper": false,
        "is_media": false,
        "jump": 0,
        "order": 1,
        "photo_answer": false,
        "photo_answer_required": false,
        "polyanswer": false,
        "record_sound": false,
        "rotation": false,
        "search": false,
        "show_images": false,
        "show_scale": false,
        "small_column": false,
        "take_photo": false,
        "title": "НОВЫЙ - Ответ",
        "unchecker": false,
        "unnecessary_fill_open": false
        },
        "queryVisibility": 0,
        "relative_id": 14,
        "relative_parent_id": 13,
        "startTime": 0,
        "type": "answer"
        }
        ],
        "endTime": 0,
        "isChecked": false,
        "isEnabled": true,
        "isQuestionShowing": false,
        "isScreenShowing": false,
        "isShuffeled": false,
        "isShuffeledIntoBox": false,
        "options": {
        "auto_check": false,
        "fixed_order": false,
        "flip_cols_and_rows": false,
        "helper": false,
        "is_media": false,
        "number": 6,
        "order": 4,
        "photo_answer": false,
        "photo_answer_required": false,
        "polyanswer": false,
        "record_sound": false,
        "rotation": false,
        "search": false,
        "show_images": false,
        "show_scale": false,
        "small_column": false,
        "take_photo": false,
        "title": "НОВЫЙ Вопрос-список посл",
        "unchecker": false,
        "unnecessary_fill_open": false
        },
        "queryVisibility": 0,
        "relative_id": 13,
        "relative_parent_id": 0,
        "startTime": 0,
        "subtype": "list",
        "type": "question"
        }
        ],
        "media_files": [],
        "name": "не сформированная квота отм",
        "project_id": 192,
        "questionnaire_id": 192
        },
        "regs_disabled": true,
        "save_aborted": false,
        "server": "license_key",
        "server_url": "http://alina.quizer.pro/_query/send-data",
        "user_project_id": 310
        }
        
*/